### ISSUE TITLE
Installation does not include all required config files

### ISSUE THREAD

**Issue by KevinVolkSTScI** [spacetelescope/mirage#109]
When I install mirage on witserv there are some required configuration files that do not get copied over to the local installation config directory.  This was also the case in the previous version that I installed.

The log below shows what happened after making a clean copy of mirage and installing it via the commands

conda create -n pipeline7.1.3 --file http://ssb.stsci.edu/releases/jwstdp/0.9.3/latest-linux
source activate pipeline7.1.3
git clone https://github.com/spacetelescope/mirage.git
cd mirage
python setup.py install

I created a new directory for testing and tried to run the code for a simple NIRISS test case.  I then compared the contents of the "config" directory for this installation that has the issue with the contents of the "config" directory on an earlier copy that works.  I had to copy a number of files over from the repository config directory to the package config directory to get the previous version working.

This appears to be a flaw in the setup.py file.  It does not copy all the required files from the git config directory to the package installation config directory.  If I copy these over manually to the package config directory then this issue is resolved.

witserv3 mirage1 > python
Python 3.5.5 |Anaconda, Inc.| (default, Apr 26 2018, 13:47:34) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nircam_simulator.scripts import imaging_simulator
>>> t1=imaging_simulator.ImgSim()
>>> t1.paramfile='niriss_imaging_test.yaml'
>>> t1.create()
'config' specified: Using /grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/nircam_simulator-1.0-py3.5.egg/nircam_simulator/config/niriss_subarrays.list for Reffiles:subarray_defs input file
'config' specified: Using /grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/nircam_simulator-1.0-py3.5.egg/nircam_simulator/config/niriss_xtalk_zeros.txt for Reffiles:crosstalk input file
'config' specified: Using /grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/nircam_simulator-1.0-py3.5.egg/nircam_simulator/config/niriss_zeropoint_values.out for Reffiles:flux_cal input file
'config' specified: Using /grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/nircam_simulator-1.0-py3.5.egg/nircam_simulator/config/niriss_readout_pattern.txt for Reffiles:readpattdefs input file
'config' specified: Using /grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/nircam_simulator-1.0-py3.5.egg/nircam_simulator/config/placeholder.txt for Reffiles:filter_throughput input file
Traceback (most recent call last):
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/nircam_simulator-1.0-py3.5.egg/nircam_simulator/scripts/catalog_seed_image.py", line 3377, in readSubarrayDefinitionFile
    self.subdict = ascii.read(self.params['Reffiles']['subarray_defs'], data_start=1, header_start=0)
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/astropy/io/ascii/ui.py", line 351, in read
    dat = _guess(table, new_kwargs, format, fast_reader)
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/astropy/io/ascii/ui.py", line 497, in _guess
    dat = reader.read(table)
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/astropy/io/ascii/core.py", line 1146, in read
    self.lines = self.inputter.get_lines(table)
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/astropy/io/ascii/core.py", line 293, in get_lines
    encoding=self.encoding) as fileobj:
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/astropy/utils/data.py", line 193, in get_readable_fileobj
    fileobj = io.FileIO(name_or_obj, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/nircam_simulator-1.0-py3.5.egg/nircam_simulator/config/niriss_subarrays.list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/nircam_simulator-1.0-py3.5.egg/nircam_simulator/scripts/imaging_simulator.py", line 60, in create
    cat.make_seed()
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/nircam_simulator-1.0-py3.5.egg/nircam_simulator/scripts/catalog_seed_image.py", line 114, in make_seed
    self.readSubarrayDefinitionFile()
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/nircam_simulator-1.0-py3.5.egg/nircam_simulator/scripts/catalog_seed_image.py", line 3379, in readSubarrayDefinitionFile
    raise RuntimeError("Error: could not read in subarray definitions file: {}".format(self.params['Reffiles']['subarray_defs']))
RuntimeError: Error: could not read in subarray definitions file: /grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/nircam_simulator-1.0-py3.5.egg/nircam_simulator/config/niriss_subarrays.list
>>>
witserv3 mirage1 > cd /grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/nircam_simulator-1.0-py3.5.egg/nircam_simulator/config/
witserv3 config > ls
dq_init.cfg                           NIRCam_zeropoints.list
__init__.py                           __pycache__
linearity.cfg                         refpix.cfg
nircam_filter_pupil_pairings.list     saturation.cfg
nircam_read_pattern_definitions.list  superbias.cfg
NIRCam_subarray_definitions.list      xtalk20150303g0.errorcut.txt
witserv3 nircam_simulator > cd /grp/jwst/nis1/kevin/anaconda3/envs/pipeline-dev/lib/python3.5/site-packages/nircam_simulator-1.0-py3.5.egg/nircam_simulator/config
witserv3 config > ls
dq_init.cfg
F070W_nircam_plus_ote_throughput_moda_sorted.txt
F070W_nircam_plus_ote_throughput_modb_sorted.txt
F090W_nircam_plus_ote_throughput_moda_sorted.txt
F090W_nircam_plus_ote_throughput_modb_sorted.txt
f090w_niriss_throughput_nopy1.txt
F115W_nircam_plus_ote_throughput_moda_sorted.txt
F115W_nircam_plus_ote_throughput_modb_sorted.txt
f115w_niriss_throughput_nopy1.txt
F140M_nircam_plus_ote_throughput_moda_sorted.txt
F140M_nircam_plus_ote_throughput_modb_sorted.txt
f140m_niriss_throughput_nopy1.txt
F150W2_nircam_plus_ote_throughput_moda_sorted.txt
F150W2_nircam_plus_ote_throughput_modb_sorted.txt
F150W_nircam_plus_ote_throughput_moda_sorted.txt
F150W_nircam_plus_ote_throughput_modb_sorted.txt
f150w_niriss_throughput_nopy1.txt
f158m_niriss_throughput_nopy1.txt
F162M_nircam_plus_ote_throughput_moda_sorted.txt
F162M_nircam_plus_ote_throughput_modb_sorted.txt
F164N_nircam_plus_ote_throughput_moda_sorted.txt
F164N_nircam_plus_ote_throughput_modb_sorted.txt
F182M_nircam_plus_ote_throughput_moda_sorted.txt
F182M_nircam_plus_ote_throughput_modb_sorted.txt
F187N_nircam_plus_ote_throughput_moda_sorted.txt
F187N_nircam_plus_ote_throughput_modb_sorted.txt
F200W_nircam_plus_ote_throughput_moda_sorted.txt
F200W_nircam_plus_ote_throughput_modb_sorted.txt
f200w_niriss_throughput_nopy1.txt
F210M_nircam_plus_ote_throughput_moda_sorted.txt
F210M_nircam_plus_ote_throughput_modb_sorted.txt
F212N_nircam_plus_ote_throughput_moda_sorted.txt
F212N_nircam_plus_ote_throughput_modb_sorted.txt
F250M_nircam_plus_ote_throughput_moda_sorted.txt
F250M_nircam_plus_ote_throughput_modb_sorted.txt
F277W_nircam_plus_ote_throughput_moda_sorted.txt
F277W_nircam_plus_ote_throughput_modb_sorted.txt
f277w_niriss_throughput_nopy1.txt
F300M_nircam_plus_ote_throughput_moda_sorted.txt
F300M_nircam_plus_ote_throughput_modb_sorted.txt
F322W2_nircam_plus_ote_throughput_moda_sorted.txt
F322W2_nircam_plus_ote_throughput_modb_sorted.txt
F323N_nircam_plus_ote_throughput_moda_sorted.txt
F323N_nircam_plus_ote_throughput_modb_sorted.txt
F335M_nircam_plus_ote_throughput_moda_sorted.txt
F335M_nircam_plus_ote_throughput_modb_sorted.txt
F356W_nircam_plus_ote_throughput_moda_sorted.txt
F356W_nircam_plus_ote_throughput_modb_sorted.txt
f356w_niriss_throughput_nopy1.txt
F360M_nircam_plus_ote_throughput_moda_sorted.txt
F360M_nircam_plus_ote_throughput_modb_sorted.txt
f380m_niriss_throughput_nopy1.txt
F405N_nircam_plus_ote_throughput_moda_sorted.txt
F405N_nircam_plus_ote_throughput_modb_sorted.txt
F410M_nircam_plus_ote_throughput_moda_sorted.txt
F410M_nircam_plus_ote_throughput_modb_sorted.txt
F430M_nircam_plus_ote_throughput_moda_sorted.txt
F430M_nircam_plus_ote_throughput_modb_sorted.txt
f430m_niriss_throughput_nopy1.txt
F444W_nircam_plus_ote_throughput_moda_sorted.txt
F444W_nircam_plus_ote_throughput_modb_sorted.txt
f444w_niriss_throughput_nopy1.txt
F460M_nircam_plus_ote_throughput_moda_sorted.txt
F460M_nircam_plus_ote_throughput_modb_sorted.txt
F466N_nircam_plus_ote_throughput_moda_sorted.txt
F466N_nircam_plus_ote_throughput_modb_sorted.txt
F470N_nircam_plus_ote_throughput_moda_sorted.txt
F470N_nircam_plus_ote_throughput_modb_sorted.txt
F480M_nircam_plus_ote_throughput_moda_sorted.txt
F480M_nircam_plus_ote_throughput_modb_sorted.txt
f480m_niriss_throughput_nopy1.txt
__init__.py
linearity.cfg
nircam_filter_pupil_pairings.list
nircam_read_pattern_definitions.list
NIRCam_subarray_definitions.list
NIRCam_zeropoints.list
niriss_dual_wheel_list.txt
niriss_readout_pattern.txt
niriss_subarrays.list
niriss_xtalk_zeros.txt
niriss_zeropoint_values.out
nsl.txt
__pycache__
refpix.cfg
saturation.cfg
superbias.cfg
xtalk20150303g0.errorcut.txt
witserv3 config > cd /ifs/jwst/wit/niriss/kevin/mirage_code_review/mirage/nircam_simulator/config
witserv3 config > ls
dq_init.cfg
F070W_nircam_plus_ote_throughput_moda_sorted.txt
F070W_nircam_plus_ote_throughput_modb_sorted.txt
F090W_nircam_plus_ote_throughput_moda_sorted.txt
F090W_nircam_plus_ote_throughput_modb_sorted.txt
f090w_niriss_throughput_nopy1.txt
F115W_nircam_plus_ote_throughput_moda_sorted.txt
F115W_nircam_plus_ote_throughput_modb_sorted.txt
f115w_niriss_throughput_nopy1.txt
F140M_nircam_plus_ote_throughput_moda_sorted.txt
F140M_nircam_plus_ote_throughput_modb_sorted.txt
f140m_niriss_throughput_nopy1.txt
F150W2_nircam_plus_ote_throughput_moda_sorted.txt
F150W2_nircam_plus_ote_throughput_modb_sorted.txt
F150W_nircam_plus_ote_throughput_moda_sorted.txt
F150W_nircam_plus_ote_throughput_modb_sorted.txt
f150w_niriss_throughput_nopy1.txt
f158m_niriss_throughput_nopy1.txt
F162M_nircam_plus_ote_throughput_moda_sorted.txt
F162M_nircam_plus_ote_throughput_modb_sorted.txt
F164N_nircam_plus_ote_throughput_moda_sorted.txt
F164N_nircam_plus_ote_throughput_modb_sorted.txt
F182M_nircam_plus_ote_throughput_moda_sorted.txt
F182M_nircam_plus_ote_throughput_modb_sorted.txt
F187N_nircam_plus_ote_throughput_moda_sorted.txt
F187N_nircam_plus_ote_throughput_modb_sorted.txt
F200W_nircam_plus_ote_throughput_moda_sorted.txt
F200W_nircam_plus_ote_throughput_modb_sorted.txt
f200w_niriss_throughput_nopy1.txt
F210M_nircam_plus_ote_throughput_moda_sorted.txt
F210M_nircam_plus_ote_throughput_modb_sorted.txt
F212N_nircam_plus_ote_throughput_moda_sorted.txt
F212N_nircam_plus_ote_throughput_modb_sorted.txt
F250M_nircam_plus_ote_throughput_moda_sorted.txt
F250M_nircam_plus_ote_throughput_modb_sorted.txt
F277W_nircam_plus_ote_throughput_moda_sorted.txt
F277W_nircam_plus_ote_throughput_modb_sorted.txt
f277w_niriss_throughput_nopy1.txt
F300M_nircam_plus_ote_throughput_moda_sorted.txt
F300M_nircam_plus_ote_throughput_modb_sorted.txt
F322W2_nircam_plus_ote_throughput_moda_sorted.txt
F322W2_nircam_plus_ote_throughput_modb_sorted.txt
F323N_nircam_plus_ote_throughput_moda_sorted.txt
F323N_nircam_plus_ote_throughput_modb_sorted.txt
F335M_nircam_plus_ote_throughput_moda_sorted.txt
F335M_nircam_plus_ote_throughput_modb_sorted.txt
F356W_nircam_plus_ote_throughput_moda_sorted.txt
F356W_nircam_plus_ote_throughput_modb_sorted.txt
f356w_niriss_throughput_nopy1.txt
F360M_nircam_plus_ote_throughput_moda_sorted.txt
F360M_nircam_plus_ote_throughput_modb_sorted.txt
f380m_niriss_throughput_nopy1.txt
F405N_nircam_plus_ote_throughput_moda_sorted.txt
F405N_nircam_plus_ote_throughput_modb_sorted.txt
F410M_nircam_plus_ote_throughput_moda_sorted.txt
F410M_nircam_plus_ote_throughput_modb_sorted.txt
F430M_nircam_plus_ote_throughput_moda_sorted.txt
F430M_nircam_plus_ote_throughput_modb_sorted.txt
f430m_niriss_throughput_nopy1.txt
F444W_nircam_plus_ote_throughput_moda_sorted.txt
F444W_nircam_plus_ote_throughput_modb_sorted.txt
f444w_niriss_throughput_nopy1.txt
F460M_nircam_plus_ote_throughput_moda_sorted.txt
F460M_nircam_plus_ote_throughput_modb_sorted.txt
F466N_nircam_plus_ote_throughput_moda_sorted.txt
F466N_nircam_plus_ote_throughput_modb_sorted.txt
F470N_nircam_plus_ote_throughput_moda_sorted.txt
F470N_nircam_plus_ote_throughput_modb_sorted.txt
F480M_nircam_plus_ote_throughput_moda_sorted.txt
F480M_nircam_plus_ote_throughput_modb_sorted.txt
f480m_niriss_throughput_nopy1.txt
guider1_throughput_py.txt
guider2_throughput_py.txt
guider_readout_pattern.txt
guider_xtalk_zeros.txt
__init__.py
linearity.cfg
nircam_filter_pupil_pairings.list
nircam_read_pattern_definitions.list
NIRCam_subarray_definitions.list
NIRCam_zeropoints.list
niriss_dual_wheel_list.txt
niriss_readout_pattern.txt
niriss_subarrays.list
niriss_xtalk_zeros.txt
niriss_zeropoint_values.out
refpix.cfg
saturation.cfg
superbias.cfg
xtalk20150303g0.errorcut.txt

**Comment by KevinVolkSTScI** [comment]
Another possible issue is that I see the NIRISS filter throughputs are the _nopy versions (no photon yield).  That is not what I want, at least when the photon yield is not in the code.  One can debate whether the photon yield is needed, as it only affects the noise properties of sources and one has to make a fairly detailed analysis to detect this difference.  To the extent that the code should simulate the noise as well as possible this should be included, but it is something that makes the code a lot slower if it is used, and maybe for routine simulations it is not worth the time cost.  I think I provided both the photon yield version and the no photon yield version of each filter throughput file.  The conversion from magnitude to count rate for NIRISS does include the photon yield so the throughput values should as well.
