### ISSUE TITLE
NIRISS simulations are not working in the current version of mirage

### ISSUE THREAD

**Issue by KevinVolkSTScI** [spacetelescope/mirage#110]
After getting the config problems described in the previous issue (#109) I tried again to run the test of NIRISS imaging.  It fails as shown below.  Running the same test with my earlier version of the simulator code works without any issues.  I do not know what has changed to cause this problem.

witserv3 mirage1 > python
Python 3.5.5 |Anaconda, Inc.| (default, Apr 26 2018, 13:47:34) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nircam_simulator.scripts import imaging_simulator
>>> t1=imaging_simulator.ImgSim()
>>> t1.paramfile='niriss_imaging_test.yaml'
>>> t1.create()
'config' specified: Using /grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/nircam_simulator-1.0-py3.5.egg/nircam_simulator/config/niriss_subarrays.list for Reffiles:subarray_defs input file
'config' specified: Using /grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/nircam_simulator-1.0-py3.5.egg/nircam_simulator/config/niriss_xtalk_zeros.txt for Reffiles:crosstalk input file
'config' specified: Using /grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/nircam_simulator-1.0-py3.5.egg/nircam_simulator/config/niriss_zeropoint_values.out for Reffiles:flux_cal input file
'config' specified: Using /grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/nircam_simulator-1.0-py3.5.egg/nircam_simulator/config/niriss_readout_pattern.txt for Reffiles:readpattdefs input file
'config' specified: Using /grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/nircam_simulator-1.0-py3.5.egg/nircam_simulator/config/placeholder.txt for Reffiles:filter_throughput input file
Requested readout pattern NISRAPID is valid. Using the nframe = 1 and nskip = 0
No galaxy catalog provided in yaml file.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/nircam_simulator-1.0-py3.5.egg/nircam_simulator/scripts/imaging_simulator.py", line 60, in create
    cat.make_seed()
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/nircam_simulator-1.0-py3.5.egg/nircam_simulator/scripts/catalog_seed_image.py", line 115, in make_seed
    self.checkParams()
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/nircam_simulator-1.0-py3.5.egg/nircam_simulator/scripts/catalog_seed_image.py", line 3037, in checkParams
    (self.zps['Filter'] == self.params['Readout'][usefilt]) &
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/astropy/table/table.py", line 1222, in __getitem__
    return self.columns[item]
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/astropy/table/table.py", line 106, in __getitem__
    return OrderedDict.__getitem__(self, item)
KeyError: 'Detector'

**Comment by KevinVolkSTScI** [comment]
Looking at the code for including FGS I see that a 'detector' parameter has been added.  This explains the issue.
