### ISSUE TITLE
Non-sidereal observations fail for readpatterns other than RAPID

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/mirage#170]
The same observation as below but using RAPID ngroup=10 runs successfully. No sources in the fov just means that the non-sidereal source is not in the fov. There are plenty of background stars present.
This is during the re-creation of the moving target data for DMS testing, in:
data4/nrc/hilbert/simulated_data/moving_target_test/AAA_REDO_Sept2018

witserv3:/home/hilbert $ python run_simulator.py 
Requested readout pattern SHALLOW4 is valid. Using the nframe = 4 and nskip = 1
No galaxy catalog provided in yaml file.
NOTE: Using pre-delivery SIAF data
Frametime is 10.736770000000002
Creating signal ramp of synthetic inputs
Point list input positions assumed to be in units of RA and Dec.
No point source catalog index numbers. Adding to output: /ifs/jwst/wit/witserv/data4/nrc/hilbert/simulated_data/moving_target_test/AAA_REDO_Sept2018/jw42424001001_01101_00001_nrcb5_uncal_pointsources.list.
After point sources, max index is 1
Number of point sources found within the requested aperture: 0
INFO: no point sources within the requested array.
Traceback (most recent call last):
  File "run_simulator.py", line 12, in <module>
    m.create()
  File "/user/hilbert/anaconda2/envs/mirage_linux/lib/python3.6/site-packages/mirage-2.1.1-py3.6.egg/mirage/imaging_simulator.py", line 57, in create
    cat.make_seed()
  File "/user/hilbert/anaconda2/envs/mirage_linux/lib/python3.6/site-packages/mirage-2.1.1-py3.6.egg/mirage/seed_image/catalog_seed_image.py", line 140, in make_seed
    self.seedimage, self.seed_segmap = self.non_sidereal_seed()
  File "/user/hilbert/anaconda2/envs/mirage_linux/lib/python3.6/site-packages/mirage-2.1.1-py3.6.egg/mirage/seed_image/catalog_seed_image.py", line 559, in non_sidereal_seed
    non_sidereal_ramp[integ, i, :, :] = nonsidereal_countrate * tmptimes[i]
IndexError: index 6 is out of bounds for axis 1 with size 6

**Comment by bhilbert4** [comment]
See PR #176.
