### ISSUE TITLE
Zero frame shape errors when trying to run a sub-array model with the NIRISS WFSS branch

### ISSUE THREAD

**Issue by KevinVolkSTScI** [spacetelescope/mirage#272]
I am trying to run a simple imaging model in the NIRISS SUB64 sub-array, using the branch that has the NIRISS WFSS mode changes.  I get errors of the following sort after the ramp seems to be generated:

Base cosmic ray probability per pixel per second: 3.0863448000000003e-06
Integration 0:
    Averaging frame 0 into group 0
    Averaging frame 1 into group 1
Traceback (most recent call last):
  File "./runmodels.py", line 47, in <module>
    t1.create()
  File "/grp/jwst/nis1/kevin/anaconda3/envs/mirage_linux_wfss/lib/python3.6/site-packages/mirage-0.0.0.dev545+gedcac073-py3.6.egg/mirage/imaging_simulator.py", line 77, in create
    obs.create()
  File "/grp/jwst/nis1/kevin/anaconda3/envs/mirage_linux_wfss/lib/python3.6/site-packages/mirage-0.0.0.dev545+gedcac073-py3.6.egg/mirage/ramp_generator/obs_generator.py", line 991, in create
    syn_zeroframe=simzero)
  File "/grp/jwst/nis1/kevin/anaconda3/envs/mirage_linux_wfss/lib/python3.6/site-packages/mirage-0.0.0.dev545+gedcac073-py3.6.egg/mirage/ramp_generator/obs_generator.py", line 473, in add_synthetic_to_dark
    zeroframe = dark.zeroframe + syn_zeroframe
ValueError: operands could not be broadcast together with shapes (1,0,0) (1,64,64) 

All I have been able to trace is that the dark ramp has a bad zero frame.  In this particular instance a raw dark is used and the linearized dark is generated.  I see the following in the log before the error

Linearized dark shape: (1, 2, 64, 64)
Output is NISRAPID, grabbing zero frame from linearized dark
Linearized dark frame plus superbias and referencepixel signals, as well as zeroframe, saved to /ifs/jwst/wit/niriss/kevin/car1094_simulations/long1_uncal_linear_dark_prep_object.fits. This can be used as input to the observationgenerator.

None the less, the code does not have a suitable zero frame.  When I looked at the code it seemed that for NIRISS the first frame of the dark is just taken for the zero frame, but that does not explain how an error could occur as above.

**Comment by KevinVolkSTScI** [comment]
After discussion with @bhilbert4 this appears to be due to using a subarray dark as input to Mirage.  While this is something we may want to allow Mirage to do later in some way, for now I am closing the issue.
