### ISSUE TITLE
Seed image generator fails with WLP4

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/mirage#455]
I was attempting to create some imaging time series data in the SW channel, with WLP4 and CLEAR, and Mirage failed with the Traceback below. Looking at my previous testing that used weak lenses, it looks like perhaps I've always tested with a filter+weak lens combination (e.g. F182M+WLP8)? Perhaps we just need to add a system throughput curve for WLP4+instrument+OTE?

Running catalog_seed_image..

From CRDS, found /Users/hilbert/crds_cache/references/jwst/nircam/jwst_nircam_mask_0033.fits as the badpixmask reference file.
From CRDS, found /Users/hilbert/crds_cache/references/jwst/nircam/jwst_nircam_superbias_0026.fits as the superbias reference file.
From CRDS, found /Users/hilbert/crds_cache/references/jwst/nircam/jwst_nircam_linearity_0056.fits as the linearity reference file.
From CRDS, found /Users/hilbert/crds_cache/references/jwst/nircam/jwst_nircam_saturation_0064.fits as the saturation reference file.
From CRDS, found /Users/hilbert/crds_cache/references/jwst/nircam/jwst_nircam_gain_0050.fits as the gain reference file.
From CRDS, found /Users/hilbert/crds_cache/references/jwst/nircam/jwst_nircam_flat_0290.fits as the pixelflat reference file.
From CRDS, found /Users/hilbert/crds_cache/references/jwst/nircam/jwst_nircam_ipc_0026.fits as the ipc reference file.
Found an existing inverted kernel for this IPC file: /Users/hilbert/crds_cache/references/jwst/nircam/Kernel_to_add_IPC_effects_from_jwst_nircam_ipc_0026.fits
From CRDS, found /Users/hilbert/crds_cache/references/jwst/nircam/jwst_nircam_distortion_0093.asdf as the astrometric reference file.
From CRDS, found /Users/hilbert/crds_cache/references/jwst/nircam/jwst_nircam_area_0017.fits as the pixelAreaMap reference file.
Requested readout pattern SHALLOW2 is valid. Using the nframe = 2 and nskip = 3
No galaxy catalog provided in yaml file.
Multiple parent apertures: NRCA1_FULL; NRCA5_GRISM256_F444W
SIAF: Requested NRCA1_GRISMTS256   got NRCA1_GRISMTS256
Calculating background rate using jwst_background based on low level
Using /Users/hilbert/python_repos/mirage/mirage/config/WLP4_nircam_plus_ote_throughput_moda_sorted.txt filter throughput file for background calculation.
Traceback (most recent call last):
  File "create_data.py", line 119, in <module>
    create_data()
  File "create_data.py", line 50, in create_data
    run_simulator(yaml_file)
  File "create_data.py", line 112, in run_simulator
    img_sim_custom_yamls.create()
  File "/Users/hilbert/python_repos/mirage/mirage/imaging_simulator.py", line 51, in create
    cat.make_seed()
  File "/Users/hilbert/python_repos/mirage/mirage/seed_image/catalog_seed_image.py", line 132, in make_seed
    self.check_params()
  File "/Users/hilbert/python_repos/mirage/mirage/seed_image/catalog_seed_image.py", line 4268, in check_params
    level=self.params['simSignals']['bkgdrate'].lower())
  File "/Users/hilbert/python_repos/mirage/mirage/utils/backgrounds.py", line 71, in calculate_background
    filt_wav, filt_thru = read_filter_throughput(filter_file)
  File "/Users/hilbert/python_repos/mirage/mirage/utils/file_io.py", line 42, in read_filter_throughput
    tab = ascii.read(filename)
  File "/Users/hilbert/miniconda3/envs/mirage/lib/python3.6/site-packages/astropy/io/ascii/ui.py", line 287, in read
    dat = _guess(table, new_kwargs, format, fast_reader)
  File "/Users/hilbert/miniconda3/envs/mirage/lib/python3.6/site-packages/astropy/io/ascii/ui.py", line 446, in _guess
    dat = reader.read(table)
  File "/Users/hilbert/miniconda3/envs/mirage/lib/python3.6/site-packages/astropy/io/ascii/core.py", line 1164, in read
    self.lines = self.inputter.get_lines(table)
  File "/Users/hilbert/miniconda3/envs/mirage/lib/python3.6/site-packages/astropy/io/ascii/core.py", line 305, in get_lines
    encoding=self.encoding) as fileobj:
  File "/Users/hilbert/miniconda3/envs/mirage/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/Users/hilbert/miniconda3/envs/mirage/lib/python3.6/site-packages/astropy/utils/data.py", line 193, in get_readable_fileobj
    fileobj = io.FileIO(name_or_obj, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hilbert/python_repos/mirage/mirage/config/WLP4_nircam_plus_ote_throughput_moda_sorted.txt'

**Comment by bhilbert4** [comment]
The above issue was solved with the weak lens work done in XXX, but I uncovered another issue. The gridded PSF libraries for WLP4+CLEAR had incorrect filter and pupil values in their headers. They had F212N in the filter value and WLP4 in the pupil value. These were from WebbPSF 0.8.0. WLP4 throughput is very close to F212N, which is I think is why WebbPSF used these values. In any case, I updated the header keywords in the PSF libraries. No code changes were necessary. 

- [ ] Still need to tar up the modified PSF libraries and upload to Box as updated reference fles.
