### ISSUE TITLE
Extended sources without rotation causing FFT to fail

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/mirage#596]
A strange bug that I don't understand yet.

When the user supplies an extended source, if the position angle of that source is set to None in the source catalog (which specifies not to rotate the stamp image), then when that stamp image is convolved with the PSF in make_extended_source_image() at this line:

                # Convolve the extended image with the stamp image
                stamp = s1.fftconvolve(stamp, psf_image, mode='same')

Mirage crashes with a traceback indicating that the data are an unsupported data type. See below for traceback. However, with even a minimal rotation applied, the convolution then seems to work fine. In both cases the stamp image is a numpy array with float32 values. The only difference is the array size. There is some padding around the edges with pixels that have a value of 0 in the case that the minimal rotation is applied. I'm stumped as to how this can be.

2020-12-11 15:54:29,942 - root - CRITICAL - Traceback (most recent call last):
  File "/Users/hilbert/python_repos/mirage/mirage/logging/logging_functions.py", line 111, in wrapped
    func(*args, **kwargs)
  File "/Users/hilbert/python_repos/mirage/mirage/seed_image/catalog_seed_image.py", line 361, in make_seed
    self.seedimage, self.seed_segmap = self.create_sidereal_image()
  File "/Users/hilbert/python_repos/mirage/mirage/seed_image/catalog_seed_image.py", line 2373, in create_sidereal_image
    extimage, ext_segmap = self.make_extended_source_image(extlist, extstamps)
  File "/Users/hilbert/python_repos/mirage/mirage/seed_image/catalog_seed_image.py", line 4675, in make_extended_source_image
    stamp = s1.fftconvolve(stamp, psf_image, mode='same')
  File "/Users/hilbert/miniconda3/envs/mirage/lib/python3.6/site-packages/scipy/signal/signaltools.py", line 542, in fftconvolve
    ret = _freq_domain_conv(in1, in2, axes, shape, calc_fast_len=True)
  File "/Users/hilbert/miniconda3/envs/mirage/lib/python3.6/site-packages/scipy/signal/signaltools.py", line 382, in _freq_domain_conv
    sp1 = fft(in1, fshape, axes=axes)
  File "/Users/hilbert/miniconda3/envs/mirage/lib/python3.6/site-packages/scipy/fft/_backend.py", line 23, in __ua_function__
    return fn(*args, **kwargs)
  File "/Users/hilbert/miniconda3/envs/mirage/lib/python3.6/site-packages/scipy/fft/_pocketfft/basic.py", line 186, in r2cn
    return pfft.r2c(tmp, axes, forward, norm, None, workers)
RuntimeError: unsupported data type

**Comment by bhilbert4** [comment]
It seems that this was actually a bug in scipy's fftconvolve: https://github.com/scipy/scipy/pull/11534
I must have upgraded to the problematic version at some point. I just updated to scipy 1.5.4 and the error no longer shows up.
