### ISSUE TITLE
Mirage v2.1.0 incompatible with jwst v1.2.3

### ISSUE THREAD

**Issue by micaelabagley** [spacetelescope/mirage#704]
It seems that Mirage v2.1.0 installs with jwst v1.1.0 and is not compatible with version 1.2.3. When forcing an install of v1.2.3, I get the following:

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mirage 2.1.0 requires jwst==1.1.0, but you have jwst 1.2.3 which is incompatible.`

Additionally, if I try to run Mirage uncals that were created with v2.1.0 through jwst v1.2.3, Detector1Pipeline fails while saving the model with the following traceback:

```
----------------------------------------------------------------------
ERROR RUNNING STEP 'Detector1Pipeline':
    '3' is not of type 'integer'  Failed validating 'type' in schema['
    properties']['meta']['properties']['dither']['properties']['dither
    _points']:     OrderedDict([('title', 'Number of points in image
    dither pattern'),                  ('type', 'integer'),
    ('fits_keyword', 'NRIMDTPT'),                  ('blend_table',
    True)])  On instance['meta']['dither']['dither_points']:     '3'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work2/05947/mbagley/stampede2/software/miniconda3/envs/mirage/bin/strun", line 28, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/work2/05947/mbagley/stampede2/software/miniconda3/envs/mirage/lib/python3.7/site-packages/stpipe/step.py", line 173, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/work2/05947/mbagley/stampede2/software/miniconda3/envs/mirage/lib/python3.7/site-packages/stpipe/cmdline.py", line 339, in step_from_cmdline
    step.run(*positional)
  File "/work2/05947/mbagley/stampede2/software/miniconda3/envs/mirage/lib/python3.7/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/work2/05947/mbagley/stampede2/software/miniconda3/envs/mirage/lib/python3.7/site-packages/jwst/pipeline/calwebb_detector1.py", line 146, in process
    self.save_model(ints_model, 'rateints')
  File "/work2/05947/mbagley/stampede2/software/miniconda3/envs/mirage/lib/python3.7/site-packages/stpipe/step.py", line 925, in save_model
    **components
  File "/work2/05947/mbagley/stampede2/software/miniconda3/envs/mirage/lib/python3.7/site-packages/stdatamodels/model_base.py", line 512, in save
    self.to_fits(output_path, *args, **kwargs)
  File "/work2/05947/mbagley/stampede2/software/miniconda3/envs/mirage/lib/python3.7/site-packages/stdatamodels/model_base.py", line 624, in to_fits
    hdulist, tree = fits_support.to_fits(self._instance, self._schema)
  File "/work2/05947/mbagley/stampede2/software/miniconda3/envs/mirage/lib/python3.7/site-packages/stdatamodels/fits_support.py", line 416, in to_fits
    _save_from_schema(hdulist, tree, schema)
  File "/work2/05947/mbagley/stampede2/software/miniconda3/envs/mirage/lib/python3.7/site-packages/stdatamodels/fits_support.py", line 352, in _save_from_schema
    validator.validate(tree, _schema=schema)
  File "/work2/05947/mbagley/stampede2/software/miniconda3/envs/mirage/lib/python3.7/site-packages/jsonschema/validators.py", line 353, in validate
    raise error
jsonschema.exceptions.ValidationError: '3' is not of type 'integer'

Failed validating 'type' in schema['properties']['meta']['properties']['dither']['properties']['dither_points']:
    OrderedDict([('title', 'Number of points in image dither pattern'),
                 ('type', 'integer'),
                 ('fits_keyword', 'NRIMDTPT'),
                 ('blend_table', True)])

On instance['meta']['dither']['dither_points']:
    '3'

```

**Comment by kammerje** [comment]
Hi, I just wanted to report the same issue! The problem is that version 1.2.3 of the JWST pipeline uses the NRIMDTPT header keyword (type int) which is not populated by version 2.1.0 of MIRAGE. Previous versions of the JWST pipeline used the NDITHPTS header keyword (type str) instead which contains the same value as the NRIMDTPT header keyword (just in a different data type, I think?!). On my side, I can get things working when manually adding the NRIMDTPT header keyword to my simulated MIRAGE data with the same value as the NDITHPTS header keyword, just as int instead of str.
