### ISSUE TITLE
Simulator fails with raw dark and multiple integrations

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/mirage#87]
The simulator fails in dark_prep.py when requesting an exposure with multiple integrations and starting with a raw dark. It completes successfully when requesting multiple integrations but starting with a linearized dark.

Traceback for this error is below. It looks like when reading in the raw dark to create duplicate integrations, the code is looking for a `zero` attribute, which isn't there (but is there in the linearized dark).
``
Requested readout pattern RAPID is valid. Using the nframe = 1 and nskip = 0
Dark shape as read in: (1, 5, 2048, 2048)
Requested output has 2 integrations, while input dark has only 1.
Adding integrations to input dark by making copies of the input.
Traceback (most recent call last):
  File "test_simulator.py", line 8, in <module>
    m.create()
  File "/ifs/jwst/wit/nircam/hilbert/python_repos/nircam_simulator/nircam_simulator/scripts/imaging_simulator.py", line 70, in create
    d.prepare()
  File "/ifs/jwst/wit/nircam/hilbert/python_repos/nircam_simulator/nircam_simulator/scripts/dark_prep.py", line 98, in prepare
    self.darkints()
  File "/ifs/jwst/wit/nircam/hilbert/python_repos/nircam_simulator/nircam_simulator/scripts/dark_prep.py", line 744, in darkints
    self.integration_copy(reqints, ndarkints)
  File "/ifs/jwst/wit/nircam/hilbert/python_repos/nircam_simulator/nircam_simulator/scripts/dark_prep.py", line 759, in integration_copy
    copyzero = self.dark.zero
AttributeError: 'Read_fits' object has no attribute 'zero'``

**Comment by bhilbert4** [comment]
Fixed with #101
